apiVersion: v1
kind: ConfigMap
metadata:
  name: bedrock-config
  namespace: minecraft
  labels:
    app: bedrock-server
data:
  server.properties: |
    server-name=Hugos Minecraft
    gamemode=creative
    force-gamemode=false
    difficulty=normal
    allow-cheats=false
    max-players=6
    online-mode=true
    allow-list=false
    server-port=19132
    server-portv6=19133
    enable-lan-visibility=true
    view-distance=10
    tick-distance=3
    player-idle-timeout=30
    max-threads=2
    level-name=Hugos Bedrock level
    level-seed=
    default-player-permission-level=member
    texturepack-required=false
    content-log-file-enabled=false
    content-log-console-output-enabled=false
    content-log-level=info
    compression-threshold=256
    compression-algorithm=snappy
    server-authoritative-movement-strict=true
    server-authoritative-dismount-strict=false
    server-authoritative-entity-interactions-strict=false
    player-position-acceptance-threshold=0.5
    player-movement-action-direction-threshold=0.85
    server-authoritative-block-breaking-pick-range-scalar=1.5
    chat-restriction=None
    disable-player-interaction=false
    client-side-chunk-generation-enabled=true
    block-network-ids-are-hashes=true
    disable-persona=false
    disable-custom-skins=false
    server-build-radius-ratio=Disabled
    allow-outbound-script-debugging=false
    allow-inbound-script-debugging=false
    script-debugger-auto-attach=disabled
    enable-query=true
    emit-server-telemetry=true
