apiVersion: v1
kind: Service
metadata:
  name: bedrock-server
  namespace: minecraft
  labels:
    app: bedrock-server
spec:
  type: NodePort
  selector:
    app: bedrock-server
  ports:
  - name: bedrock-ipv4
    port: 19132
    targetPort: 19132
    protocol: UDP
    nodePort: 31932
  - name: bedrock-ipv6
    port: 19133
    targetPort: 19133
    protocol: UDP
    nodePort: 31933
  externalTrafficPolicy: Local
